default:
  # This does not seem to work as of now...
  image: gpuci/miniconda-cuda:11.0-devel-ubuntu16.04

  cache:
    paths:
      - .cache/

  before_script:
    - ls
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O .cache/miniconda.sh
   # - conda env create -f environment.yml
   # - conda activate cbi_toolbox
    #- python -v

test:
  script:
    - echo "test"
    #- python -m unittest
    #- python -c "import cbi_toolbox.cudaradon"


#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc ; make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
