default:
  #image: gpuci/miniconda-cuda:11.0-devel-ubuntu16.04

  before_script:
    - python3 -v
    - pip3 --version
    - pip3 install .

test:
  script:
    - python -m unittest
    #- python -c "import cbi_toolbox.cudaradon"


#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc ; make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
