default:
  # This does not seem to work as of now...
  #image: gpuci/miniconda-cuda:11.0-devel-ubuntu16.04

  before_script:
    - gcc --version
    - mpicc --version
   # - conda activate cbi_toolbox
    #- python -v

test:
  script:
    - python -v
    #- python -m unittest
    #- python -c "import cbi_toolbox.cudaradon"


#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc ; make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
