variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  #image: gpuci/miniconda-cuda:11.0-devel-ubuntu16.04

  before_script:
    - python3 --version
    - pip3 install --upgrade pip setuptools wheel
    - pip3 --version
    - pip3 install . -v

  cache:
    paths:
      - .cache/pip

test:
  script:
    - python3 -m unittest
    #- python -c "import cbi_toolbox.cudaradon"


#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc ; make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
