variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:

  before_script:
    - pip3 install --upgrade pip setuptools wheel
    - python3 -m venv .venv
    - source .venv/bin/activate
    - python --version
    - pip --version
    - which pip
    - pip install .

  after_script:
    - rm -rf .venv

test:
  script:
    - cd tests
    - python -m unittest


#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc ; make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
