variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:

  before_script:
    - pip3 install --upgrade pip setuptools wheel
    - pip3 install pipenv
    - PIPENV_VENV_IN_PROJECT=1 pipenv install .
    - pipenv run python --version

  after_script:
    - pipenv --rm

test:
  script:
    - cd tests
    - pipenv run python -m unittest


#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc ; make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
