variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  #image: gpuci/miniconda-cuda:11.0-devel-ubuntu16.04

  before_script:
    - python3 --version
    - pip3 install --upgrade pip setuptools wheel
    - pip3 install pipenv
    - PIPENV_VENV_IN_PROJECT=1 pipenv shell
    - which python
    - which pip
    - pip install .

  after_script:
    - pipenv --rm

test:
  script:
    - cd tests
    - python -m unittest


#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc ; make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
