name: cbi_toolbox
channels:
  - conda-forge
  - defaults
dependencies:
  - cmake>=3.18*
  - pybind11>=2.6*
  - noise>=1.2*
  - scipy>=1.4*
  - python>=3*
  - numpy>=1.17*
  - gxx_linux-64>=6*
  - pip
  - pip:
    - mpi4py
    - opencv-python
    - apeer-ometiff-library
    - poppy
