name: cbi_toolbox
channels:
  - conda-forge
  - defaults
dependencies:
  - cmake>=3.18*
  - noise>=1.2*
  - scipy>=1.4*
  - scikit-image
  - python>=3*
  - numpy>=1.17*
  - gxx_linux-64>=6*
  - pip
  - pip:
      - opencv-python
      - mpi4py
      - apeer-ometiff-library
      - poppy
