# Copyright (c) 2020 Idiap Research Institute, http://www.idiap.ch/
# Written by François Marelli <francois.marelli@idiap.ch>

# This file is part of CBI Toolbox.

# CBI Toolbox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.

# CBI Toolbox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with CBI Toolbox. If not, see <http://www.gnu.org/licenses/>.

name: cbi_toolbox
channels:
  - conda-forge
  - defaults
dependencies:
  - cmake>=3.18*
  - cxx-compiler
  - python>=3.7*
  - numpy>=1.17*
  - scipy>=1.4*
  - noise>=1.2*
  - scikit-image
  - mpi4py
  - pip
  - pip:
      - opencv-python
      - apeer-ometiff-library
      - poppy
