{% set data = load_setup_py_data() %}

package:
  name: cbi_toolbox
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script: python -m pip install .[plots] -vv
  noarch: python

requirements:
  build:
    - python >=3*
    - setuptools

  run:
    - cmake >=3.18*
    - python >=3*
    - numpy >=1.17*
    - pybind11 >=2.2*
    - scipy >=1.4*
    - noise >=1.2*
    - mpi4py >=3*
    - opencv >=4.4*
    - matplotlib
    - napari

test:
  imports:
    - cbi_toolbox
